# Generated by Django 5.2 on 2025-05-25 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_transaccion', models.CharField(choices=[('venta', 'Venta'), ('donacion', 'Donación')], max_length=10)),
                ('descripcion', models.TextField()),
                ('estado_publicacion', models.CharField(choices=[('disponible', 'Disponible'), ('en_espera', 'En espera'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='disponible', max_length=15)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='app.libro')),
                ('user_comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_compradas', to=settings.AUTH_USER_MODEL, to_field='uid')),
                ('user_ofertador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_ofertadas', to=settings.AUTH_USER_MODEL, to_field='uid')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicaciones/')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.publicacion')),
            ],
        ),
    ]
