# Generated by Django 5.2 on 2025-04-27 02:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Perfecto', 'Perfecto'), ('Con detalles', 'Con detalles'), ('Desgastado', 'Desgastado'), ('En malas condiciones', 'En malas condiciones')], max_length=50)),
                ('genero', models.CharField(max_length=100)),
                ('paginas', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='libros/')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.libro')),
            ],
        ),
    ]
