# Generated by Django 5.2 on 2025-04-20 04:09

import uuid
from django.db import migrations, models

def generar_uids_para_usuarios(apps, schema_editor):
    Usuario = apps.get_model('app', 'Usuario')
    for usuario in Usuario.objects.all():
        usuario.uid = uuid.uuid4()
        usuario.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),  # ← actualiza esto si es necesario
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, null=True),  # ← importante dejarlo null=True temporalmente
        ),
        migrations.RunPython(generar_uids_para_usuarios),
        migrations.AlterField(
            model_name='usuario',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),  # ← ya sin null
        ),
    ]
