# Generated by Django 5.2 on 2025-04-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_libro_imagenlibro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='anno_nacimiento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
