# Generated by Django 5.2 on 2025-06-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_publicacion_imagenpublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('conversation_notified', True)), fields=('sender', 'recipient', 'conversation_notified'), name='unique_conversation_notification'),
        ),
    ]
