# Generated by Django 5.2 on 2025-05-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usuario_preferencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='preferencias',
            field=models.CharField(blank=True, choices=[('Comedia', 'Comedia'), ('Romance', 'Romance'), ('Terror', 'Terror'), ('Misterio', 'Misterio'), ('Finanzas', 'Finanzas'), ('Psicologia', 'Psicologia'), ('Fantasia', 'Fantasia'), ('otro', 'otro')], default='', max_length=50),
        ),
    ]
