# Generated by Django 5.2 on 2025-06-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuario_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='confirmacion_comprador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='confirmacion_ofertador',
            field=models.BooleanField(default=False),
        ),
    ]
