# Generated by Django 5.2 on 2025-05-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_libro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
