# Generated by Django 5.2 on 2025-06-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_publicacion_confirmacion_comprador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='confirmacion_comprador',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='confirmacion_ofertador',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado_publicacion',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_espera', 'En espera'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='disponible', max_length=15),
        ),
    ]
