# Generated by Django 5.2 on 2025-05-14 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_libro_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion_comprador', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valoracion_ofertador', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_como_comprador', to=settings.AUTH_USER_MODEL)),
                ('ofertador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_como_ofertador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
