# Generated by Django 5.2 on 2025-05-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_valoracion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Valoracion',
        ),
    ]
