# Generated by Django 5.2 on 2025-06-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_publicacion_estado_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='ticket_comprador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='ticket_ofertador',
            field=models.BooleanField(default=False),
        ),
    ]
