# Generated by Django 5.2 on 2025-06-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_publicacion_ticket_comprador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado_publicacion',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('disponible', 'Disponible'), ('en_espera', 'En espera'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], default='disponible', max_length=15),
        ),
    ]
