# Generated by Django 5.2 on 2025-06-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_publicacion_estado_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenpublicacion',
            name='publicacion',
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ImagenLibro',
        ),
        migrations.DeleteModel(
            name='ImagenPublicacion',
        ),
    ]
