# Generated by Django 5.2 on 2025-06-25 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_imagenpublicacion_publicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen_url',
        ),
        migrations.CreateModel(
            name='ImagenLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='libros/')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.libro')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicaciones/')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.publicacion')),
            ],
        ),
    ]
