# Generated by Django 5.2 on 2025-06-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_libro_imagen_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado_publicacion',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('disponible', 'Disponible'), ('en_espera', 'En espera'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pendiente', 'Pendiente'), ('cancel_history', 'Cancelado (Histórico)')], default='disponible', max_length=15),
        ),
    ]
