# Generated by Django 5.2 on 2025-04-20 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='img_perfil',
            field=models.ImageField(blank=True, default='img/perfil.jpg', null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
